<a href="https://colab.research.google.com/github/tashir0605/Cocepts-And-Practice/blob/main/Pytorch/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


# Create a Tensor

In [3]:
# using empty
torch.empty(2,3)

tensor([[-2.4754e-35,  4.5349e-41,  4.3026e-19],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [4]:
type(torch.empty(2,3))

torch.Tensor

In [6]:
# using zeroes

torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)

tensor([[0.6176, 0.5052, 0.8758],
        [0.7694, 0.7344, 0.0026]])

the problem with rand is that ki jb bhi iss file ko dubara run karoge to to wo value alg hongi values and if I want to work with those rand values only then there is a way of Manual seed

In [9]:
#manula seed
torch.manual_seed(42)
torch.rand(2,3)


tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

Reproducability

In [10]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [11]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
# iska mtlb O se 10 ke beech me values honi chahiye and evenly spaced of 10 values
print("using linspace ->", torch.linspace(0,10,10))

# using eye
# iska mtlb hai made a tensor of 5*5 of identity matrix
print("using eye ->", torch.eye(5))

# using full
# it is used for (3,3) signifies 3*3 ka matrix with each value with 5
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [16]:
x=torch.tensor([[1,2,3],[3,4,5]])

In [18]:
x.shape

torch.Size([2, 3])

In [20]:
# if you want to create a tensor of the same shape like the previos one you can use
torch.empty_like(x)

tensor([[   138995980017024,          675013264,                683],
        [323133281962622976, 120189815083107964,                  0]])

In [22]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [23]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [24]:
torch.rand_like(x)
# rand generate float values between 0 to 1
# this is not working because as your original tensor contain integer values but rand generate float values between 0 to 1 so that's why it's not working you have to explicitly tell that you want to generate float values

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [35]:
# Solution for the above error
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

# Tensor Data Types

In [26]:
# find data types
x.dtype

torch.int64

In [31]:
# just suppose you want to assign the data type of a tensor at the defining the tensor
torch.tensor([[1,2,3],[5,6,7] ],dtype=torch.float64)

tensor([[1., 2., 3.],
        [5., 6., 7.]], dtype=torch.float64)

In [32]:
x


tensor([[1, 2, 3],
        [3, 4, 5]])

In [34]:
# As you can see the dtype of x is integer
# agr hme bne bnaye tensor ke datatype ko change krna hai then
x.to(torch.float32)

tensor([[1., 2., 3.],
        [3., 4., 5.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |

# MAthematical Operations